-- =========================================================================
-- ATUALIZAÇÃO SENSE: PLANEJADOR DE POSTS NA NUVEM
-- =========================================================================

CREATE TABLE posts_planejador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    image TEXT,
    caption TEXT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE posts_planejador ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo posts_planejador" ON posts_planejador FOR ALL USING (true);
