-- =========================================================================
-- ATUALIZAÇÃO SENSE: MÓDULO DE SUPORTE TÉCNICO (HELPDESK)
-- =========================================================================

-- Cria a tabela principal de Tickets
CREATE TABLE suporte_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remetente_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    categoria VARCHAR(100) NOT NULL,
    assunto VARCHAR(255) NOT NULL,
    prioridade VARCHAR(50) DEFAULT 'Média',
    descricao TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'Aberto', -- Aberto, Em andamento, Fechado
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE suporte_tickets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo suporte_tickets" ON suporte_tickets FOR ALL USING (true);

-- Cria a tabela de Mensagens vinculadas aos Tickets
CREATE TABLE suporte_mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT REFERENCES suporte_tickets(id) ON DELETE CASCADE,
    remetente_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    mensagem TEXT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE suporte_mensagens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo suporte_mensagens" ON suporte_mensagens FOR ALL USING (true);
