-- =========================================================================
-- BANCO DE DADOS SENSE (SINGLE-AGENCY)
-- Simplificado para uso exclusivo, sem multi-tenancy (sem agencia_id)
-- =========================================================================

-- Limpeza total
DROP TABLE IF EXISTS historico_clientes CASCADE;
DROP TABLE IF EXISTS arquivos CASCADE;
DROP TABLE IF EXISTS financeiro CASCADE;
DROP TABLE IF EXISTS conteudos CASCADE;
DROP TABLE IF EXISTS projetos CASCADE;
DROP TABLE IF EXISTS notificacoes CASCADE;
DROP TABLE IF EXISTS metricas CASCADE;
DROP TABLE IF EXISTS automacoes_logs CASCADE;
DROP TABLE IF EXISTS entregas CASCADE;
DROP TABLE IF EXISTS comentarios_tarefas CASCADE;
DROP TABLE IF EXISTS checklists_tarefas CASCADE;
DROP TABLE IF EXISTS tarefas CASCADE;
DROP TABLE IF EXISTS leads CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS atlas_logs CASCADE;
-- 2. Clientes (CRM)
CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    responsavel_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    nome VARCHAR(255) NOT NULL,
    empresa VARCHAR(255),
    nicho VARCHAR(255),
    logo TEXT,
    email VARCHAR(255),
    telefone VARCHAR(50),
    whatsapp VARCHAR(50),
    cpf_cnpj VARCHAR(50),
    endereco TEXT,
    cidade VARCHAR(100),
    estado VARCHAR(50),
    cep VARCHAR(20),
    servico VARCHAR(255) NOT NULL,
    mrr DECIMAL(10,2) DEFAULT 0.00,
    data_inicio DATE,
    data_renovacao DATE,
    plano VARCHAR(255),
    status_geral VARCHAR(50) DEFAULT 'Ativo',
    tags JSONB DEFAULT '[]'::jsonb,
    segmento VARCHAR(100),
    prioridade VARCHAR(50) DEFAULT 'Média',
    observacoes TEXT,
    progresso INT DEFAULT 0,
    proxima_entrega DATE,
    pendencia_atual VARCHAR(255),
    instagram_url TEXT,
    dia_pagamento INT,
    entregas_mensais INT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo clientes" ON clientes FOR ALL USING (true);

-- 3. Leads (Comercial)
CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa VARCHAR(255) NOT NULL,
    contato VARCHAR(255) NOT NULL,
    telefone VARCHAR(50) NOT NULL,
    email VARCHAR(255),
    origem VARCHAR(100),
    valor_estimado DECIMAL(10,2) DEFAULT 0.00,
    status VARCHAR(50) DEFAULT 'Prospect',
    nota_ia DECIMAL(3,1),
    resumo_ia TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo leads" ON leads FOR ALL USING (true);

-- 4. Tarefas e Reuniões
CREATE TABLE tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    responsavel_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    titulo VARCHAR(255) NOT NULL,
    setor VARCHAR(50) NOT NULL,
    prioridade VARCHAR(50) DEFAULT 'Média',
    status VARCHAR(50) DEFAULT 'A fazer',
    prazo TIMESTAMP WITH TIME ZONE, -- Corrigido para TIME ZONE para Reuniões não perderem a hora
    link_entrega TEXT,
    comentarios JSONB DEFAULT '[]'::jsonb,
    checklists JSONB DEFAULT '[]'::jsonb,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE tarefas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo tarefas" ON tarefas FOR ALL USING (true);

-- 5. Métricas (Resultados / Scraping)
CREATE TABLE metricas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    data_registro DATE NOT NULL,
    seguidores INT DEFAULT 0,
    alcance INT DEFAULT 0,
    engajamento DECIMAL(5,2) DEFAULT 0.00,
    leads INT DEFAULT 0,
    cliques_site INT DEFAULT 0,
    tipo VARCHAR(50) DEFAULT 'Mensal',
    anotacao TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE metricas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo metricas" ON metricas FOR ALL USING (true);

-- 6. Projetos
CREATE TABLE projetos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    responsavel_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    nome VARCHAR(255) NOT NULL,
    tipo VARCHAR(100),
    progresso INT DEFAULT 0,
    data_inicio DATE,
    prazo DATE,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE projetos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo projetos" ON projetos FOR ALL USING (true);

-- 7. Conteúdos (Posts, Vídeos)
CREATE TABLE conteudos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    tipo VARCHAR(50) NOT NULL, -- Post, Vídeo, Story, etc.
    titulo VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'Em produção',
    data_criacao TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE conteudos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo conteudos" ON conteudos FOR ALL USING (true);

-- 8. Financeiro
CREATE TABLE financeiro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    descricao TEXT NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    vencimento DATE NOT NULL,
    status VARCHAR(50) DEFAULT 'Pendente',
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE financeiro ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo financeiro" ON financeiro FOR ALL USING (true);

-- 9. Arquivos (Documentos, Contratos)
CREATE TABLE arquivos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    nome VARCHAR(255) NOT NULL,
    categoria VARCHAR(100),
    url TEXT NOT NULL,
    data_upload TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE arquivos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo arquivos" ON arquivos FOR ALL USING (true);

-- 10. Histórico de Ações de Clientes
CREATE TABLE historico_clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    usuario VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    data_registro TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE historico_clientes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo historico_clientes" ON historico_clientes FOR ALL USING (true);

-- 11. Notificações Internas
CREATE TABLE notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensagem TEXT NOT NULL,
    tipo VARCHAR(50) DEFAULT 'info',
    lida BOOLEAN DEFAULT false,
    link TEXT,
    data_criacao TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE notificacoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo notificacoes" ON notificacoes FOR ALL USING (true);

-- 12. Automacões Logs (Opcional, para robôs internos)
CREATE TABLE automacoes_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acao VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'Sucesso',
    detalhes JSONB DEFAULT '{}'::jsonb,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE automacoes_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo automacoes" ON automacoes_logs FOR ALL USING (true);

-- INSERIR O USUÁRIO ADMINISTRADOR PADRÃO DA SENSE
INSERT INTO usuarios (nome, email, funcao, avatar_url)
VALUES ('Admin', 'admin@sense.com', 'Administrador', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin');

-- INSERIR GABI (A senha no sistema atual não é checada, basta o email para o protótipo)
INSERT INTO usuarios (nome, email, funcao, avatar_url)
VALUES ('Gabi', 'gabi@sense.com', 'Comercial', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gabi');

-- 13. Suporte Técnico (Tickets)
CREATE TABLE suporte_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remetente_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    categoria VARCHAR(100) NOT NULL,
    assunto VARCHAR(255) NOT NULL,
    prioridade VARCHAR(50) DEFAULT 'Média',
    descricao TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'Aberto', -- Aberto, Em andamento, Fechado
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo usuarios" ON usuarios FOR ALL USING (true);

-- 2. Clientes (CRM)
CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    responsavel_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    nome VARCHAR(255) NOT NULL,
    empresa VARCHAR(255),
    nicho VARCHAR(255),
    logo TEXT,
    email VARCHAR(255),
    telefone VARCHAR(50),
    whatsapp VARCHAR(50),
    cpf_cnpj VARCHAR(50),
    endereco TEXT,
    cidade VARCHAR(100),
    estado VARCHAR(50),
    cep VARCHAR(20),
    servico VARCHAR(255) NOT NULL,
    mrr DECIMAL(10,2) DEFAULT 0.00,
    data_inicio DATE,
    data_renovacao DATE,
    plano VARCHAR(255),
    status_geral VARCHAR(50) DEFAULT 'Ativo',
    tags JSONB DEFAULT '[]'::jsonb,
    segmento VARCHAR(100),
    prioridade VARCHAR(50) DEFAULT 'Média',
    observacoes TEXT,
    progresso INT DEFAULT 0,
    proxima_entrega DATE,
    pendencia_atual VARCHAR(255),
    instagram_url TEXT,
    dia_pagamento INT,
    entregas_mensais INT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo clientes" ON clientes FOR ALL USING (true);

-- 3. Leads (Comercial)
CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    empresa VARCHAR(255) NOT NULL,
    contato VARCHAR(255) NOT NULL,
    telefone VARCHAR(50) NOT NULL,
    email VARCHAR(255),
    origem VARCHAR(100),
    valor_estimado DECIMAL(10,2) DEFAULT 0.00,
    status VARCHAR(50) DEFAULT 'Prospect',
    nota_ia DECIMAL(3,1),
    resumo_ia TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo leads" ON leads FOR ALL USING (true);

-- 4. Tarefas e Reuniões
CREATE TABLE tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    responsavel_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    titulo VARCHAR(255) NOT NULL,
    setor VARCHAR(50) NOT NULL,
    prioridade VARCHAR(50) DEFAULT 'Média',
    status VARCHAR(50) DEFAULT 'A fazer',
    prazo TIMESTAMP WITH TIME ZONE, -- Corrigido para TIME ZONE para Reuniões não perderem a hora
    link_entrega TEXT,
    comentarios JSONB DEFAULT '[]'::jsonb,
    checklists JSONB DEFAULT '[]'::jsonb,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE tarefas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo tarefas" ON tarefas FOR ALL USING (true);

-- 5. Métricas (Resultados / Scraping)
CREATE TABLE metricas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    data_registro DATE NOT NULL,
    seguidores INT DEFAULT 0,
    alcance INT DEFAULT 0,
    engajamento DECIMAL(5,2) DEFAULT 0.00,
    leads INT DEFAULT 0,
    cliques_site INT DEFAULT 0,
    tipo VARCHAR(50) DEFAULT 'Mensal',
    anotacao TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE metricas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo metricas" ON metricas FOR ALL USING (true);

-- 6. Projetos
CREATE TABLE projetos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    responsavel_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    nome VARCHAR(255) NOT NULL,
    tipo VARCHAR(100),
    progresso INT DEFAULT 0,
    data_inicio DATE,
    prazo DATE,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE projetos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo projetos" ON projetos FOR ALL USING (true);

-- 7. Conteúdos (Posts, Vídeos)
CREATE TABLE conteudos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    tipo VARCHAR(50) NOT NULL, -- Post, Vídeo, Story, etc.
    titulo VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'Em produção',
    data_criacao TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE conteudos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo conteudos" ON conteudos FOR ALL USING (true);

-- 8. Financeiro
CREATE TABLE financeiro (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    descricao TEXT NOT NULL,
    valor DECIMAL(10,2) NOT NULL,
    vencimento DATE NOT NULL,
    status VARCHAR(50) DEFAULT 'Pendente',
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE financeiro ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo financeiro" ON financeiro FOR ALL USING (true);

-- 9. Arquivos (Documentos, Contratos)
CREATE TABLE arquivos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    nome VARCHAR(255) NOT NULL,
    categoria VARCHAR(100),
    url TEXT NOT NULL,
    data_upload TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE arquivos ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo arquivos" ON arquivos FOR ALL USING (true);

-- 10. Histórico de Ações de Clientes
CREATE TABLE historico_clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    usuario VARCHAR(255) NOT NULL,
    descricao TEXT NOT NULL,
    data_registro TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE historico_clientes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo historico_clientes" ON historico_clientes FOR ALL USING (true);

-- 11. Notificações Internas
CREATE TABLE notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mensagem TEXT NOT NULL,
    tipo VARCHAR(50) DEFAULT 'info',
    lida BOOLEAN DEFAULT false,
    link TEXT,
    data_criacao TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE notificacoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo notificacoes" ON notificacoes FOR ALL USING (true);

-- 12. Automacões Logs (Opcional, para robôs internos)
CREATE TABLE automacoes_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acao VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'Sucesso',
    detalhes JSONB DEFAULT '{}'::jsonb,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE automacoes_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo automacoes" ON automacoes_logs FOR ALL USING (true);

-- INSERIR O USUÁRIO ADMINISTRADOR PADRÃO DA SENSE
INSERT INTO usuarios (nome, email, funcao, avatar_url)
VALUES ('Admin', 'admin@sense.com', 'Administrador', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Admin');

-- INSERIR GABI (A senha no sistema atual não é checada, basta o email para o protótipo)
INSERT INTO usuarios (nome, email, funcao, avatar_url)
VALUES ('Gabi', 'gabi@sense.com', 'Comercial', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Gabi');

-- 13. Suporte Técnico (Tickets)
CREATE TABLE suporte_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    remetente_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    categoria VARCHAR(100) NOT NULL,
    assunto VARCHAR(255) NOT NULL,
    prioridade VARCHAR(50) DEFAULT 'Média',
    descricao TEXT NOT NULL,
    status VARCHAR(50) DEFAULT 'Aberto', -- Aberto, Em andamento, Fechado
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE suporte_tickets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo suporte_tickets" ON suporte_tickets FOR ALL USING (true);

-- 14. Mensagens do Suporte (Chat)
CREATE TABLE suporte_mensagens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT REFERENCES suporte_tickets(id) ON DELETE CASCADE,
    remetente_id BIGINT REFERENCES usuarios(id) ON DELETE CASCADE,
    mensagem TEXT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE suporte_mensagens ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo suporte_mensagens" ON suporte_mensagens FOR ALL USING (true);

-- 15. Posts Planejador (Calendário de Redes Sociais)
CREATE TABLE posts_planejador (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    date DATE NOT NULL,
    image TEXT, -- Pode ser Base64 ou URL da imagem
    caption TEXT NOT NULL,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE posts_planejador ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo posts_planejador" ON posts_planejador FOR ALL USING (true);
