-- ==========================================
-- ATLAS OS - SCHEMA (SAAS MULTI-TENANT)
-- ==========================================

-- 1. Apagar tabelas se existirem para evitar conflitos na migração
DROP TABLE IF EXISTS automacoes_logs CASCADE;
DROP TABLE IF EXISTS leads CASCADE;
DROP TABLE IF EXISTS notificacoes CASCADE;
DROP TABLE IF EXISTS metricas CASCADE;
DROP TABLE IF EXISTS entregas CASCADE;
DROP TABLE IF EXISTS tarefas CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS agencias CASCADE;

-- 2. Agências (Tenants)
CREATE TABLE agencias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    logo_url TEXT,
    tema_cores JSONB DEFAULT '{}'::jsonb,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE agencias ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo agencias" ON agencias FOR ALL USING (true);

-- 3. Usuarios (Time da Agência e Clientes)
CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencia_id BIGINT REFERENCES agencias(id) ON DELETE CASCADE,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    funcao VARCHAR(50) NOT NULL, -- 'Admin', 'Designer', 'Social Media', 'Cliente'
    avatar_url TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE usuarios ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo usuarios" ON usuarios FOR ALL USING (true);

-- 4. Clientes (Empresas atendidas pela Agência)
CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencia_id BIGINT REFERENCES agencias(id) ON DELETE CASCADE,
    nome VARCHAR(255) NOT NULL,
    servico VARCHAR(255),
    status_geral VARCHAR(50) DEFAULT 'em_dia',
    progresso INT DEFAULT 0,
    proxima_entrega DATE,
    dados_metricas JSONB DEFAULT '{}'::jsonb,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo clientes" ON clientes FOR ALL USING (true);

-- 5. Tarefas (Módulo Operacional)
CREATE TABLE tarefas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencia_id BIGINT REFERENCES agencias(id) ON DELETE CASCADE,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    responsavel_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    titulo VARCHAR(255) NOT NULL,
    setor VARCHAR(50) NOT NULL,
    prioridade VARCHAR(50) DEFAULT 'Média',
    status VARCHAR(50) DEFAULT 'A fazer',
    prazo DATE,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE tarefas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo tarefas" ON tarefas FOR ALL USING (true);

-- 6. Entregas (Materiais atrelados a Tarefas)
CREATE TABLE entregas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencia_id BIGINT REFERENCES agencias(id) ON DELETE CASCADE,
    tarefa_id BIGINT REFERENCES tarefas(id) ON DELETE CASCADE,
    autor_id BIGINT REFERENCES usuarios(id) ON DELETE SET NULL,
    tipo VARCHAR(50) NOT NULL, -- 'Arte', 'Video', 'Texto'
    url_material TEXT,
    status VARCHAR(50) DEFAULT 'Aguardando Aprovação',
    versao INT DEFAULT 1,
    notas_correcao TEXT,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE entregas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo entregas" ON entregas FOR ALL USING (true);

-- 7. Metricas
CREATE TABLE metricas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencia_id BIGINT REFERENCES agencias(id) ON DELETE CASCADE,
    cliente_id BIGINT REFERENCES clientes(id) ON DELETE CASCADE,
    data_registro DATE NOT NULL,
    seguidores INT DEFAULT 0,
    alcance INT DEFAULT 0,
    engajamento DECIMAL(5,2) DEFAULT 0.00,
    leads INT DEFAULT 0,
    tipo VARCHAR(50) DEFAULT 'mensal',
    anotacao TEXT
);
ALTER TABLE metricas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo metricas" ON metricas FOR ALL USING (true);

-- 8. Notificacoes
CREATE TABLE notificacoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencia_id BIGINT REFERENCES agencias(id) ON DELETE CASCADE,
    mensagem TEXT NOT NULL,
    tipo VARCHAR(50) DEFAULT 'info',
    lida BOOLEAN DEFAULT false,
    link TEXT,
    data_criacao TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE notificacoes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo notificacoes" ON notificacoes FOR ALL USING (true);

-- 9. Leads (CRM / Pipeline Comercial)
CREATE TABLE leads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencia_id BIGINT REFERENCES agencias(id) ON DELETE CASCADE,
    empresa VARCHAR(255) NOT NULL,
    contato VARCHAR(255) NOT NULL,
    telefone VARCHAR(50),
    email VARCHAR(255),
    origem VARCHAR(100),
    valor_estimado DECIMAL(10,2) DEFAULT 0,
    status VARCHAR(50) DEFAULT 'Prospect',
    nota_ia INT,
    resumo_ia TEXT,
    data_criacao TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo leads" ON leads FOR ALL USING (true);

-- 10. Automações Logs
CREATE TABLE automacoes_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agencia_id BIGINT REFERENCES agencias(id) ON DELETE CASCADE,
    referencia_id BIGINT,
    tipo VARCHAR(50) NOT NULL,
    acao VARCHAR(255) NOT NULL,
    status VARCHAR(50) DEFAULT 'Sucesso',
    detalhes JSONB DEFAULT '{}'::jsonb,
    criado_em TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE automacoes_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Permitir tudo automacoes" ON automacoes_logs FOR ALL USING (true);
